[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.mypy]
check_untyped_defs = true
disable_error_code = ["empty-body"]
disallow_untyped_defs = false
strict = true

[tool.poetry]
name = "agentic"
version = "0.1.0"
description = "Integrate LLMs as Python functions"
authors = ["Jack Collins"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10"
openai = ">=0.27"
pydantic = "*"

[tool.poetry.group.dev.dependencies]
black = "*"
mypy = "*"
pytest = "*"
pytest-clarity = "*"
