[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "agentic"
version = "0.1.0"
description = "Integrate LLMs as Python functions"
authors = ["Jack Collins"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8"
openai = ">=0.27"
pydantic = "*"

[tool.poetry.group.dev.dependencies]
black = "*"
pytest = "*"
