[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
preview = true

[tool.isort]
profile = "black"

[tool.mypy]
check_untyped_defs = true
disable_error_code = ["empty-body"]
disallow_untyped_defs = false
strict = true

[tool.poetry]
name = "magentic"
version = "0.1.2"
description = "Seamlessly integrate LLMs as Python functions"
license = "MIT"
authors = ["Jack Collins"]
readme = "README.md"
repository = "https://github.com/jackmpcollins/magentic"

[tool.poetry.dependencies]
python = ">=3.10"
openai = ">=0.27"
pydantic = ">=2.0.0"

[tool.poetry.group.dev.dependencies]
black = "*"
isort = "*"
mypy = "*"
pytest = "*"
pytest-clarity = "*"
pytest-cov = "*"

[tool.poetry.group.examples.dependencies]
jupyter = "*"

[tool.pytest.ini_options]
addopts = "--cov=magentic"
markers = [
    "openai: Tests that query the OpenAI API"
]

[tool.ruff]
line-length = 120

[tool.ruff.isort]
known-first-party = ["magentic"]

[tool.ruff.extend-per-file-ignores]
"__init__.py" = ["F401"]
